# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Trubi.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class TrUi_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 611)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 793, 550))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.labelDiametrNaruzh1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelDiametrNaruzh1.setGeometry(QtCore.QRect(10, 50, 141, 16))
        self.labelDiametrNaruzh1.setObjectName("labelDiametrNaruzh1")
        self.labelDiametrZamka1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelDiametrZamka1.setGeometry(QtCore.QRect(10, 90, 151, 16))
        self.labelDiametrZamka1.setObjectName("labelDiametrZamka1")
        self.labelTolshina1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelTolshina1.setGeometry(QtCore.QRect(10, 130, 111, 16))
        self.labelTolshina1.setObjectName("labelTolshina1")
        self.labelDlinaTrubi = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelDlinaTrubi.setGeometry(QtCore.QRect(10, 180, 91, 16))
        self.labelDlinaTrubi.setObjectName("labelDlinaTrubi")
        self.labelDlinaZamka = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelDlinaZamka.setGeometry(QtCore.QRect(10, 230, 131, 16))
        self.labelDlinaZamka.setObjectName("labelDlinaZamka")
        self.labelKoeff = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelKoeff.setGeometry(QtCore.QRect(10, 260, 211, 16))
        self.labelKoeff.setObjectName("labelKoeff")
        self.labelVnutrneniyDiametr = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelVnutrneniyDiametr.setGeometry(QtCore.QRect(10, 290, 171, 16))
        self.labelVnutrneniyDiametr.setObjectName("labelVnutrneniyDiametr")
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setGeometry(QtCore.QRect(150, 50, 133, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 90, 133, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 0, 795, 552))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 793, 550))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.labelDiametrNaruzh1_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelDiametrNaruzh1_2.setGeometry(QtCore.QRect(10, 50, 141, 16))
        self.labelDiametrNaruzh1_2.setObjectName("labelDiametrNaruzh1_2")
        self.labelDiametrZamka1_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelDiametrZamka1_2.setGeometry(QtCore.QRect(10, 90, 151, 16))
        self.labelDiametrZamka1_2.setObjectName("labelDiametrZamka1_2")
        self.labelTolshina1_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelTolshina1_2.setGeometry(QtCore.QRect(10, 130, 111, 16))
        self.labelTolshina1_2.setObjectName("labelTolshina1_2")
        self.labelDlinaTrubi1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelDlinaTrubi1.setGeometry(QtCore.QRect(10, 180, 91, 16))
        self.labelDlinaTrubi1.setObjectName("labelDlinaTrubi1")
        self.labelDlinaZamka1_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelDlinaZamka1_2.setGeometry(QtCore.QRect(10, 230, 131, 16))
        self.labelDlinaZamka1_2.setObjectName("labelDlinaZamka1_2")
        self.labelKoeff1_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelKoeff1_2.setGeometry(QtCore.QRect(10, 280, 211, 16))
        self.labelKoeff1_2.setObjectName("labelKoeff1_2")
        self.labelVnutrneniyDiametr1_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelVnutrneniyDiametr1_2.setGeometry(QtCore.QRect(10, 330, 171, 16))
        self.labelVnutrneniyDiametr1_2.setObjectName("labelVnutrneniyDiametr1_2")
        self.DiametrNaruzh1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.DiametrNaruzh1.setGeometry(QtCore.QRect(150, 50, 133, 20))
        self.DiametrNaruzh1.setObjectName("DiametrNaruzh1")
        self.DiametrZamka1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.DiametrZamka1.setGeometry(QtCore.QRect(170, 90, 133, 20))
        self.DiametrZamka1.setObjectName("DiametrZamka1")
        self.Tolshina1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.Tolshina1.setGeometry(QtCore.QRect(120, 130, 133, 20))
        self.Tolshina1.setObjectName("Tolshina1")
        self.Dlinatrubi1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.Dlinatrubi1.setGeometry(QtCore.QRect(110, 180, 133, 20))
        self.Dlinatrubi1.setObjectName("Dlinatrubi1")
        self.DlinaZamka1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.DlinaZamka1.setGeometry(QtCore.QRect(150, 230, 133, 20))
        self.DlinaZamka1.setObjectName("DlinaZamka1")
        self.Koeff1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.Koeff1.setGeometry(QtCore.QRect(220, 280, 133, 20))
        self.Koeff1.setObjectName("Koeff1")
        self.VnutrneniyDiametr1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.VnutrneniyDiametr1.setEnabled(False)
        self.VnutrneniyDiametr1.setGeometry(QtCore.QRect(180, 330, 133, 20))
        self.VnutrneniyDiametr1.setObjectName("VnutrneniyDiametr1")
        self.VnutrneniyDiametr2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.VnutrneniyDiametr2.setEnabled(False)
        self.VnutrneniyDiametr2.setGeometry(QtCore.QRect(590, 330, 133, 20))
        self.VnutrneniyDiametr2.setObjectName("VnutrneniyDiametr2")
        self.Dlinatrubi2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.Dlinatrubi2.setGeometry(QtCore.QRect(520, 180, 133, 20))
        self.Dlinatrubi2.setObjectName("Dlinatrubi2")
        self.labelTolshina2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelTolshina2.setGeometry(QtCore.QRect(420, 130, 111, 16))
        self.labelTolshina2.setObjectName("labelTolshina2")
        self.labelVnutrneniyDiametr2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelVnutrneniyDiametr2.setGeometry(QtCore.QRect(420, 330, 171, 16))
        self.labelVnutrneniyDiametr2.setObjectName("labelVnutrneniyDiametr2")
        self.labelDlinaZamka2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelDlinaZamka2.setGeometry(QtCore.QRect(420, 230, 131, 16))
        self.labelDlinaZamka2.setObjectName("labelDlinaZamka2")
        self.labelDiametrNaruzh2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelDiametrNaruzh2.setGeometry(QtCore.QRect(420, 50, 141, 16))
        self.labelDiametrNaruzh2.setObjectName("labelDiametrNaruzh2")
        self.labelKoeff2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelKoeff2.setGeometry(QtCore.QRect(420, 280, 211, 16))
        self.labelKoeff2.setObjectName("labelKoeff2")
        self.Tolshina2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.Tolshina2.setGeometry(QtCore.QRect(530, 130, 133, 20))
        self.Tolshina2.setObjectName("Tolshina2")
        self.labelDiametrZamka2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelDiametrZamka2.setGeometry(QtCore.QRect(420, 90, 151, 16))
        self.labelDiametrZamka2.setObjectName("labelDiametrZamka2")
        self.DiametrZamka2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.DiametrZamka2.setGeometry(QtCore.QRect(580, 90, 133, 20))
        self.DiametrZamka2.setObjectName("DiametrZamka2")
        self.labelDlinaTrub2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelDlinaTrub2.setGeometry(QtCore.QRect(420, 180, 91, 16))
        self.labelDlinaTrub2.setObjectName("labelDlinaTrub2")
        self.DlinaZamka2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.DlinaZamka2.setGeometry(QtCore.QRect(560, 230, 133, 20))
        self.DlinaZamka2.setObjectName("DlinaZamka2")
        self.Koeff2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.Koeff2.setGeometry(QtCore.QRect(630, 280, 133, 20))
        self.Koeff2.setObjectName("Koeff2")
        self.DiametrNaruzh2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.DiametrNaruzh2.setGeometry(QtCore.QRect(560, 50, 133, 20))
        self.DiametrNaruzh2.setObjectName("DiametrNaruzh2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label.setObjectName("label")
        self.label1truba = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label1truba.setGeometry(QtCore.QRect(110, 10, 47, 13))
        self.label1truba.setObjectName("label1truba")
        self.label1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label1.setGeometry(QtCore.QRect(170, 10, 47, 13))
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label2.setGeometry(QtCore.QRect(520, 10, 47, 13))
        self.label2.setObjectName("label2")
        self.labelCodTruba2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelCodTruba2.setGeometry(QtCore.QRect(580, 10, 47, 13))
        self.labelCodTruba2.setObjectName("labelCodTruba2")
        self.labelTruba2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelTruba2.setGeometry(QtCore.QRect(420, 10, 101, 16))
        self.labelTruba2.setObjectName("labelTruba2")
        self.labelCodTruba1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelCodTruba1.setGeometry(QtCore.QRect(200, 10, 47, 13))
        self.labelCodTruba1.setObjectName("labelCodTruba1")
        self.CodTruba2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.CodTruba2.setGeometry(QtCore.QRect(610, 10, 47, 13))
        self.CodTruba2.setObjectName("CodTruba2")
        self.ButtonRaschet = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.ButtonRaschet.setGeometry(QtCore.QRect(320, 430, 83, 23))
        self.ButtonRaschet.setObjectName("ButtonRaschet")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Характеристики труб"))
        self.labelDiametrNaruzh1.setText(_translate("MainWindow", "<html><head/><body><p>Диаметр наружный d<span style=\" vertical-align:sub;\">n </span>:</p></body></html>"))
        self.labelDiametrZamka1.setText(_translate("MainWindow", "<html><head/><body><p>Диаметр замка (муфты) d<span style=\" vertical-align:sub;\">m  </span>:</p></body></html>"))
        self.labelTolshina1.setText(_translate("MainWindow", "<html><head/><body><p>Толщина стенки <span style=\" font-family:\'palatino linotype,new athena unicode,athena,gentium,code2000,serif\'; color:#222222; background-color:#f8f9fa;\">δ:</span></p></body></html>"))
        self.labelDlinaTrubi.setText(_translate("MainWindow", "<html><head/><body><p>Длина трубы l<span style=\" vertical-align:sub;\">o</span>:</p></body></html>"))
        self.labelDlinaZamka.setText(_translate("MainWindow", "<html><head/><body><p>Длина замка (трубы)  l<span style=\" vertical-align:sub;\">м</span>:</p></body></html>"))
        self.labelKoeff.setText(_translate("MainWindow", "<html><head/><body><p>Коэффициент учета потерь в замке K<span style=\" vertical-align:sub;\">м</span>:</p></body></html>"))
        self.labelVnutrneniyDiametr.setText(_translate("MainWindow", "<html><head/><body><p>Внутренний диаметр трубы d<span style=\" vertical-align:sub;\">b</span>:</p></body></html>"))
        self.labelDiametrNaruzh1_2.setText(_translate("MainWindow", "<html><head/><body><p>Диаметр наружный d<span style=\" vertical-align:sub;\">n </span>:</p></body></html>"))
        self.labelDiametrZamka1_2.setText(_translate("MainWindow", "<html><head/><body><p>Диаметр замка (муфты) d<span style=\" vertical-align:sub;\">m  </span>:</p></body></html>"))
        self.labelTolshina1_2.setText(_translate("MainWindow", "<html><head/><body><p>Толщина стенки <span style=\" font-family:\'palatino linotype,new athena unicode,athena,gentium,code2000,serif\'; color:#222222; background-color:#f8f9fa;\">δ:</span></p></body></html>"))
        self.labelDlinaTrubi1.setText(_translate("MainWindow", "<html><head/><body><p>Длина трубы l<span style=\" vertical-align:sub;\">o</span>:</p></body></html>"))
        self.labelDlinaZamka1_2.setText(_translate("MainWindow", "<html><head/><body><p>Длина замка (трубы)  l<span style=\" vertical-align:sub;\">м</span>:</p></body></html>"))
        self.labelKoeff1_2.setText(_translate("MainWindow", "<html><head/><body><p>Коэффициент учета потерь в замке K<span style=\" vertical-align:sub;\">м</span>:</p></body></html>"))
        self.labelVnutrneniyDiametr1_2.setText(_translate("MainWindow", "<html><head/><body><p>Внутренний диаметр трубы d<span style=\" vertical-align:sub;\">b</span>:</p></body></html>"))
        self.labelTolshina2.setText(_translate("MainWindow", "<html><head/><body><p>Толщина стенки <span style=\" font-family:\'palatino linotype,new athena unicode,athena,gentium,code2000,serif\'; color:#222222; background-color:#f8f9fa;\">δ:</span></p></body></html>"))
        self.labelVnutrneniyDiametr2.setText(_translate("MainWindow", "<html><head/><body><p>Внутренний диаметр трубы d<span style=\" vertical-align:sub;\">b</span>:</p></body></html>"))
        self.labelDlinaZamka2.setText(_translate("MainWindow", "<html><head/><body><p>Длина замка (трубы)  l<span style=\" vertical-align:sub;\">м</span>:</p></body></html>"))
        self.labelDiametrNaruzh2.setText(_translate("MainWindow", "<html><head/><body><p>Диаметр наружный d<span style=\" vertical-align:sub;\">n </span>:</p></body></html>"))
        self.labelKoeff2.setText(_translate("MainWindow", "<html><head/><body><p>Коэффициент учета потерь в замке K<span style=\" vertical-align:sub;\">м</span>:</p></body></html>"))
        self.labelDiametrZamka2.setText(_translate("MainWindow", "<html><head/><body><p>Диаметр замка (муфты) d<span style=\" vertical-align:sub;\">m  </span>:</p></body></html>"))
        self.labelDlinaTrub2.setText(_translate("MainWindow", "<html><head/><body><p>Длина трубы l<span style=\" vertical-align:sub;\">o</span>:</p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Бурильные трубы </p></body></html>"))
        self.label1truba.setText(_translate("MainWindow", "TextLabel"))
        self.label1.setText(_translate("MainWindow", "<html><head/><body><p>код</p></body></html>"))
        self.label2.setText(_translate("MainWindow", "TextLabel"))
        self.labelCodTruba2.setText(_translate("MainWindow", "<html><head/><body><p>код</p></body></html>"))
        self.labelTruba2.setText(_translate("MainWindow", "<html><head/><body><p>Бурильные трубы </p></body></html>"))
        self.labelCodTruba1.setText(_translate("MainWindow", "TextLabel"))
        self.CodTruba2.setText(_translate("MainWindow", "TextLabel"))
        self.ButtonRaschet.setText(_translate("MainWindow", "Начать расчет"))

